name: Production
on:
  push:
    branches: "main"
jobs:
  build-and-upload-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Update env
        run: |
          VUE_APP_API_URL=${{ secrets.VUE_APP_API_URL }} && sed -i 's|<VUE_APP_API_URL>|'${VUE_APP_API_URL}'|' $GITHUB_WORKSPACE/.env
          VUE_APP_TELEGRAM_FEEDBACK_BOT=${{ secrets.VUE_APP_TELEGRAM_FEEDBACK_BOT }} && sed -i 's|<VUE_APP_TELEGRAM_FEEDBACK_BOT>|'${VUE_APP_TELEGRAM_FEEDBACK_BOT}'|' $GITHUB_WORKSPACE/.env
          VUE_APP_TELEGRAM_ORDER_BOT=${{ secrets.VUE_APP_TELEGRAM_ORDER_BOT }} && sed -i 's|<VUE_APP_TELEGRAM_ORDER_BOT>|'${VUE_APP_TELEGRAM_ORDER_BOT}'|' $GITHUB_WORKSPACE/.env
          
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Deploy to S3
        run: aws s3 sync ./dist s3://pistachos-shopapp --acl public-read --follow-symlinks --delete